### ISSUE TITLE
Prepared statements

### ISSUE THREAD

**Issue by AconceptSA** [andreossido/laravel-filemaker#1]
Hi,

There is a problem with the 'parameter' function in FilemakerQueryGrammar.

All values are passed in the SQL prepared statement instead of being replaced by '?'.

It is a big security issue.

Actually, in order to avoid this problem users must extend the FilemakerQueryGrammar with their own class  and replace 2 functions.

In app/MyApp/Database/CustomFilemakerQueryGrammar.php:

```php
<?php
namespace App\MyApp\Database;

use Abram\Filemaker\FilemakerQueryGrammar as Grammar;

class CustomFilemakerQueryGrammar extends Grammar
{
    protected function wrapValue($value)
    {
        // Tables 
        return $value === '*' ? $value : '"'.str_replace('"', '\"', $value).'"';
    }

    public function parameter($value)
    {
        return $this->isExpression($value) ? $this->getValue($value) : '?';
    }
}

```
In database.php:

```php
'odbc-connection-name' => [
	'driver' => 'odbc',
	'dsn' => 'OdbcConnectionName',
	'database' => 'DatabaseName',
	'host' => '127.0.0.1',
	'username' => 'username',
	'password' => 'password',
	'options' => [
		'processor' => \Abram\Filemaker\FilemakerProcessor::class,
		'grammar' => [
			'query' => \App\MyApp\Database\CustomFilemakerQueryGrammar::class
		],
	]
]
```

**Comment by andreossido** [comment]
Yes, I know It is a big security issue
Exactly as your "fix"
If you put a backslash to escape quotes you can always do sqlinjection.
Example:
Input: `Andrea\" or 1=1 -- `
Output of your fix: `Andrea\\" or 1=1 -- `

This is an old project and It isn't written thinking about security

**Comment by AconceptSA** [comment]
Hi Andrea,

This is an old project but I am very glad it exists and would like to thank you for it. It helped me a lot for an existing project.

Concerning my fix, I think you misunderstood it. It is in the `parameter` function.

The `parameter` function place `?` in the SQL prepared statement instead of the values (subject to SQL Injection).

For the `wrapValue` function, I had an issue with table and column names and it is only extended in order to be sure to use `"` to wrap them. I am not the administrator of the FM database and some table and column names have spaces, accents... Anyway.

Now doing this with Laravel Query Builder:
```php
$user = DB::table('users')->where('name', 'Andrea\" or 1=1 --');
```
Without the fix of `parameter`:

1. SQL statement : `SELECT * FROM users WHERE "name" = "Andrea\\" or 1=1 -- "`
2. Binded values to ODBC (**they are not used**):
```
array (
  0 => 'Andrea\" or 1=1 --',
)
```

With the fix:

1. SQL statement : `SELECT * FROM users WHERE "name" = ?`
2. Binded values to ODBC (**they are used**):
```
array (
  0 => 'Andrea\" or 1=1 --',
)
```

Thank you for your time and I hope I didn't make any mistake in submitting this issue. I don't think there is much security issue than this one.

I guess it is better for users to fix your main project than forking.
